version: '3'

services:
  php:
    build: 
      context: './docker/php'
    volumes:
      - './:/var/www/html'
    user: '1000:1000'
    working_dir: '/var/www/html'
    environment:
      - DB_HOST=mysql
      - DB_NAME=database
      - DB_USERNAME=user
      - DB_PASSWORD=user
    links:
      - 'mysql:mysql'
    networks:
      - api
    depends_on:
      - mysql
  
  nginx:
    image: nginx:latest
    ports: 
      - 8080:80
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - 'php:php'
    networks:
      - api

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    networks:
      - api

networks:
  api:
    driver: bridge