version: '3'

services:
  php:
    build: 
      context: './docker/php'
    volumes:
      - './:/var/www/html'
    user: '1000:1000'
    working_dir: '/var/www/html'
    environment:
      - DB_HOST=mysql
      - DB_NAME=database
      - DB_USERNAME=user
      - DB_PASSWORD=user
    links:
      - 'mysql:mysql'
    networks:
      - api
    depends_on:
      - mysql
  
  nginx:
    image: nginx:latest
    ports: 
      - '8080:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - 'php:php'
    networks:
      - api
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    networks:
      - api

  #Сервис для разворачивания контейнера с автотестами
  tests:
   image: mrexpen/planet_olymp_phase1
#   pull_policy: always
   ports:
     - '8090:8080'
   depends_on:
     - php
   links:
     - 'nginx:nginx'
   networks:
     - api
   environment:
     SERVER_URL: http://nginx:80
     STAGE: all
    # all - запуск всех тестов из трёх доступных этапов
    # 0, 1 или 2 - запуск тестов для соответствующего этапа

networks:
  api:
    driver: bridge