version: '3.9'

services:
  php:
    build:
      context: './docker/php'
    volumes:
      - './:/var/www/html'
    depends_on:
      - nginx
      - mysql
    working_dir: '/var/www/html'
    #command: make database
    environment:
      DB_HOST: mysql
      DB_NAME: drip_chik
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: drip_chik
      MYSQL_USER: drip_chik
      MYSQL_PASSWORD: drip_chik
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'


  #Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - php
    environment:
      SERVER_URL: http://nginx:80
      STAGE: 1
    # all - запуск всех тестов из трёх доступных этапов
    # 0, 1 или 2 - запуск тестов для соответствующего этапа